VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box      = "centos/7"

  # Configure vagrant-cachier plugin
   if Vagrant.has_plugin?("vagrant-hostmanager")
       config.hostmanager.enabled = true
       config.hostmanager.manage_host = true
       config.hostmanager.ignore_private_ip = false
       config.hostmanager.include_offline = true
end

  config.vm.provision "ansible" do |ansible|
   #ansible.verbose = "vvv"
   ansible.playbook = "build.yml"
   #ansible.sudo = true
   ansible.become = true
   ansible.raw_arguments  = "--vault-password-file=vars/vault_pass.txt"
end

  config.vm.define "master" do |master|
   master.vm.hostname = "master"
   master.vm.network "forwarded_port", guest: 3306, host: 3337
   master.vm.network "private_network", ip: "192.168.50.2", virtualbox__intnet: true
end

  config.vm.define "slave" do |slave|
   slave.vm.hostname = "slave"
   slave.vm.network "forwarded_port", guest: 3306, host: 3338
   slave.vm.network "private_network", ip: "192.168.50.3", virtualbox__intnet: true
end

  config.vm.define "etl" do |etl|
   etl.vm.hostname = "etl"
   etl.vm.network "forwarded_port", guest: 3306, host: 3339
   etl.vm.network "private_network", ip: "192.168.50.4", virtualbox__intnet: true
end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    #v.memory = 1024
    v.cpus = 1
  end
end
