---
- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars_files:
      -  vars/main.yml

  tasks:


  pre_tasks:
   []


  roles:
    - percona
    - { role: proxysql, when: "ansible_hostname == 'proxysql'" }
    - { role: replication, when: "( ansible_hostname == 'slave' or ansible_hostname == 'etlslave')", tags: [ 'repl' ] }


  post_tasks:
   []
